### ISSUE TITLE
온보딩 디자인 변경

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#104]
## Description
> 설명을 작성하세요.

변경된 온보딩 디자인을 적용하려고 합니다.
홈화면 우측 상단에 위치한 느낌표 아이콘을 누르면, 온보딩 화면을 다시 확인할 수 있는데 해당 뷰에도 변경사항을 적용할 예정입니다.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/7737a8f8-44e2-4ddb-8e91-fb299e5adcf9">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/13ab7ff8-ee86-47d8-a839-4c04ee4f6cae">

</br>

## To-do

- [x] `Lottie` 적용하기
- [x] 이미지 에셋 추가하기
- [x] 온보딩 화면 수정하기 
- [x] 홈 화면 우측 상단 느낌표 아이콘 색상 수정
  - [x] 눌렀을 때 나오는 화면 수정

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
