### ISSUE TITLE
버스 아이콘 눌렀을 때 popover 화면 뜨게 하기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#110]
## Description
> 설명을 작성하세요.
버스 아이콘을 누르면 버스 아이콘 바로 하단에 popover 화면이 뜨게 합니다.
(기존에는 버스 아이콘을 누르면 화면의 최하단에 정류장 정보가 떴습니다.)

</br>

## To-do

- [ ] ToolKit, Popover 기술조사
- [ ] Popover 내부 뷰 구현
- [ ] 지도에 적용 -> (BusStopViewWrapper)에 적용 예정

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

**Comment by Minkyeong-Choi** [comment]
@dbqls200 이 이슈는 BottomSheet 관련 pr이 머지된 후 pr 올리겠습니다!
