### ISSUE TITLE
목적지 도착했을 때 사용자에게 알리기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#113]
## Description
사용자가 목적지에 도착했음을 인지할 수 있는 로직을 만들고, 사용자가 도착했음을 알 수 있는 뷰와 notification을 구현합니다.

</br>

## To-do

- [x] 도착 로직 만들기
- [x] 실제 뷰에 도착했을 때 띄울 뷰 제작하기
- [x] 도착하면 알러트 띄우기

</br>

## ETC (참고 자료)
<img width="442" alt="image" src="https://github.com/user-attachments/assets/2ef19f69-e52e-48aa-bb5c-04889f479eab">
