### ISSUE TITLE
다크모드 적용하기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#118]
## Description
> 설명을 작성하세요.

다크모드 디자인이 완료되어, 적용할 예정입니다.

</br>

## To-do

- [x] info.plist에 다크모드 지원 설정하기
- [x] 온보딩 화면에 다크모드용 json 파일 추가하기
- [x] 다크모드 잘 적용되었는지 확인하기
- [x] StopStatusEnum 수정하기
  - [x] 사용하는 변수만 두고 나머지 삭제하기
  - [ ] 색 설정 제대로 되었는지 확인하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
