### ISSUE TITLE
지도 위에 정류장 위치 표시하기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#12]
## Description
지도 위에 버스 별 정류장의 위치를 표시하는 작업을 진행합니다.

</br>

## To-do

- [x] 버스 정류장의 x, y 좌표 수집하기
- [x] 버스 별로 지도 위에 표시하기
- [x] 207번과 472번 구별해서 제공하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
