### ISSUE TITLE
207번 경로 표시하기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#131]
## Description
> 설명을 작성하세요.
- 207번 버스의 경로를 등록하고, 사용자의 출발지와 최종 목적지에 맞게 해당되는 경로만 표시해줍니다.
- 버스 정류장 아이콘의 사이즈를 줄입니다. 사용자의 여정에만 해당되는 경로와 노선의 모든 정류장을 보여주는 버스 아이콘을 대비하기 위함입니다.
</br>

## To-do

- [x] 207번 버스 경로 csv 파일 만들기
- [x] csv 파일 등록하기
- [x] 해당 경로만 출력할 수 있게 로직 사용하기
- [x] 버스 아이콘 사이즈 줄이기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
