### ISSUE TITLE
목적지 입력 후 맵뷰로 넘어가는 중에 보이는 로딩 뷰 작업하기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#132]
## Description
> 설명을 작성하세요.

사용자가 목적지 입력 후, 맵뷰로 넘어가는 중에 로딩 화면을 띄우려고 합니다.
현재는, 정류장 데이터 로드 및 계산 로직이 돌아가는 동안, 맵뷰에 정확한 데이터가 나타나지 않습니다.
사용자에게 부정확한 데이터를 전달하는 대신, 로딩 뷰를 제공하려고 합니다.

</br>

## To-do

- [x] 로딩 뷰 작업하기
- [x] 작업 status 관리하기
  - [ ] 작업 상태 enum 선언
  - [x] 로직 돌아가는 동안 진행중 상태 유지
  - [x] 진행중일 때 로딩 뷰 띄우기 

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
