### ISSUE TITLE
v1.1.0 기준 QA 반영 - 민

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#135]
## Description
> 설명을 작성하세요.

12월 2일 진행된 QA 바탕으로 수정된 사항들을 반영합니다.

</br>

## To-do

**1순위 변경사항들**
`OnboardingView`
- [x] 위치접근권한 alert가 항상 영어로 뜨게 하기 -> 불가능해서 한국어 번역을 그냥 추가해놓기로 했습니다.
- [x] 위치접근권한 description 수정하기

`ScannedJourneyInfoView`
- [x] start 버튼 눌렀을 때 notification 권한 팝업 뜨게 하기

`MapView`
- [x] DestinationView에 테두리 넣기
- [x] Tooltip vertical padding 조절하기
- [x] end 버튼 눌렀을 때 팝업에서 exit 버튼 end로 수정하기
- [x] MyLocation 이미지 다시 적용하기

- [x] 영어 수정한 것 다시 적용하기

**백로그 변경사항들 (시간이 남으면 진행해보겠습니다)**
- [ ] BusStopIcon 위로 MyLocation 이미지가 지나갈 수 있게 하기
- [ ] 새로고침이 자동으로 안돼서 이동할 때 사용자를 따라가지 않는 이슈
- [ ] Tooltip을 눌렀다가 다시 해제했을 때 Tooltip이 꺼진 그 맵 위치 그대로 남아있게 하기
- [ ] ScannedJourneyView에서 MapView로 넘어갈 때 경고 화면이 비치는 이슈

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
