### ISSUE TITLE
BusStopData.csv 파일 작업하기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#138]
## Description
> 설명을 작성하세요.

기존에서 하나의 열이 더 추가된 BusStopData 파일을 앱에 적용합니다.
아마 model을 수정하고 데이터 흐름을 건드려야할 것 같습니다.

</br>

## To-do

- [x] BusStopData 파일 넣기
- [x] 모델 수정하기
- [x] 데이터 흐름 수정하기
- [x] MapView의 EndView와 BottomSheet, tooltip에서 해석된 값이 보이게 하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
