### ISSUE TITLE
MapView 하이파이 참고해서 그리기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#24]
## Description
맵이 들어가는 뷰를 하이파이와 동일한 모습으로 그립니다.

</br>

## To-do

- [x] 파일 폴더링하기

- [x] 네비게이션 바 커스텀으로 뷰 만들기
- [x] 아래에 버스 정류장 정보에 해당하는 뷰 만들기
- [x] 사용자가 자유롭게 지도를 움직일 수 있게 하기
- [x] 사용자의 현재 위치 점이 방향도 보여주게 하기 -> 이거 하나 때문에 코드가 너무 길어질 것 같아서 나중에 시도하겠습니다...
- [x] 버스 정류장을 눌렀을 때 그 버스 정류장의 정보가 나올 수 있게 테스트하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
