### ISSUE TITLE
Live Activity View 작업

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#25]
## Description
> 설명을 작성하세요.

앱을 사용하지 않는 상황에서도, 잠금 화면 및 다이나믹 아일랜드에서 쉽게 정보를 확인하도록 돕기 위해 라이브 액티비티를 사용합니다.
라이브 액티비티로 사용자가 확인할 수 있는 데이터는 아래와 같습니다.
- <ins>하차 정류장 이름</ins>
  - 한국어 표기
  - 로마자 표기
- (사용자의 현재 위치로부터 하차 정류장까지) <ins>남은 정류장 수</ins>

<img width="250" alt="image" src="https://github.com/user-attachments/assets/9f907c09-8911-4ea7-89e4-6663ed88518f">

</br>

## To-do

- [ ] 다이나믹 아일랜드 view 작업하기
- [ ] 잠금화면 view 작업하기
- [ ] 입력 단계에서 받은 데이터 연결하기

</br>
