### ISSUE TITLE
스크린샷으로 버스 정보 불러오기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#30]
## Description
앱의 도입부에서 스크린샷 사진을 업로드하면 자동으로 필요한 값을 추출하도록 합니다.

</br>

## To-do

- [x] 로직 정리하기
- [x] 포항에 버스 번호 모두 등록하기
- [x] 1) 종류를 분류하는 로직 넣기
- [x] 2) 한 대만 운행하는 루트일 때 텍스트 추출하기
- [x] 3) 여러 대 운행하는 루트일 때 텍스트 추출하기
- [x] 4) 한 스크린샷에 여러 루트가 떴을 때 대처하기

</br>

## ETC (참고 자료)
추후 pr에 로직 정리해서 그림으로 올리도록 하겠습니다!
