### ISSUE TITLE
MapView 하이파이에 맞게 수정하기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#41]
## Description
> 설명을 작성하세요.
MapView를 하이파이에 맞게 수정합니다.

</br>

## To-do

- [x] MapView -> BusStopView로 이름 변경 (하이파이 파일명에 맞춤)
- [x] BusSearchViewModel에서 이번 정류장 정보 가져오기
- [x] ThisStopView 만들기 (이번 정류장 뷰)
- [x] EndStopView 만들기 (최종 정류장 뷰)
- [x] 사용자 현재 위치 점 모양 커스텀 

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
