### ISSUE TITLE
Onboarding 화면 작업

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#42]
## Description
> 설명을 작성하세요.

처음 앱을 사용할 때, 스크린샷을 통해 정보 입력하는 방식에 대한 설명이 필요합니다.
사용자가 업로드한 스크린샷을 통해, `출발정류장` / `하차정류장` / `버스번호`에 대한 데이터를 받아옵니다.

<img width="750" alt="image" src="https://github.com/user-attachments/assets/5ddfd9cc-b42b-4ec7-af39-0cd051f9f4e1">

</br>

## To-do

- [x] 맨 처음 앱 설치하고 진입할 때, 자동으로 온보딩 화면 띄우기 (그 이후에는 자동으로 띄우지 않음.)
  - [x] UserDefault에 제일 처음 진입인지 판단하는 변수 저장하기
- [x] 홈 화면 우측 상단 아이콘을 누르면, 온보딩 화면 다시 확인할 수 있도록 하기
- [x] image asset 추가하기
- [x] 버튼 컴포넌트 만들기
- [ ] 모아나가 color asset 추가해주면, 색상 적용하기
- [ ] 서체 적용 후, 수정하기

</br>
