### ISSUE TITLE
HomeView 스크린샷 업로드 뷰 그리기

### ISSUE THREAD

**Issue by Minkyeong-Choi** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#49]
## Description
> 설명을 작성하세요.
HomeView의 스크린샷 업로드 뷰를 그리는 이슈입니다.

</br>

## To-do

- [x] 사진을 업로드하는 화면
- [x] PhotoPicker 기능
- [x] 인식 후 정보를 보여주는 화면
- [x] 업로드 후 정보를 수정하는 화면

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
