### ISSUE TITLE
Pretendard 서체 적용하기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#76]
## Description
> 설명을 작성하세요.

앱 내 모든 텍스트 요소에 Pretendard 서체를 적용하여 디자인팀이 설정한 스타일 가이드에 맞추어 UI 개선을 진행할 예정입니다.

</br>

## To-do

- [x] Pretendard 서체 다운 받기
- [ ] Font Extension 만들기
- [ ] 이미 작성된 view에 서체 적용하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
