### ISSUE TITLE
472번 각 버스 정류장 데이터에 로마자 표기 데이터 추가하기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#9]
## Description
> 설명을 작성하세요.

기존에 472번 버스 노선의 모든 정류장 정보가 담긴 CSV 파일이 있습니다.
이 파일에 각 버스 정류장에 대한 한국어 로마자 표기를 추가하고자 합니다.

</br>

## To-do

- [x] 서울시 전체 버스를 다루는 데이터에서 472번에 대한 데이터만 추출하기
- [x] 한국어 로마자 표기 데이터 추가하기
- [x] csv 파일 파싱하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

[한국어 로마자 변환기](http://roman.cs.pusan.ac.kr/)
