### ISSUE TITLE
맵뷰 bottom sheet View 그리기

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#99]
## Description
> 설명을 작성하세요.

맵뷰 하단에 bottom sheet view를 구현하려고 합니다.

<img src="https://github.com/user-attachments/assets/19e73c73-34a3-4908-ac8a-29c7cbfe099a" width=300> <img src="https://github.com/user-attachments/assets/533aed56-6f42-4eea-8556-f5079145d2cd" width=300>

</br>

## To-do

- [x] `SwiftUI`에서 `sheet` 하단 고정 가능한지 알아보기
- [x] `sheet` 내부 view 구현하기
  - [x] 사용자가 탑승하는 버스 번호에 해당하는 모든 정류장 나열하기
  - [x] 경로에 해당하지 않는 정류장은 회색 처리, 경로에 해당하는 정류장만 노란 표시하기
  - [ ] 현재 지나가고 있는 정류장에 버스 아이콘 표시하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
